cmake_minimum_required(VERSION 3.24)
project(spixprobe LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_AUTORCC ON)
find_package(Qt6 REQUIRED COMPONENTS Core Gui Qml Quick)
find_package(Spix REQUIRED)
find_package(SpixQtQuick REQUIRED)
find_package(AnyRPC REQUIRED)
qt_add_executable(spixprobe main.cpp resources.qrc)
target_link_libraries(spixprobe PRIVATE Qt6::Quick Spix::SpixCore Spix::SpixQtQuick AnyRPC::anyrpc)
